Update default test configuration for the daemons
Alignak-monitoring/alignak pull request #840
Opened 2017-05-31 08:52 UTC by mohierf

Update with the most recent alignak default configuration 

Closes #810: remove Example module declared for each daemon

2017-05-31 17:56 UTC, mohierf commented
@ddurieux : please have a look to the 2 failing tests ... I do not understand why they fail whereas they should not!

2017-06-05 20:41 UTC, ddurieux requested changes

2017-06-05 20:41 UTC, ddurieux commented on alignak/objects/config.py
> +        # # Check that a default realm (and only one) is defined
remove these comment lines, if not need them, delete them ;)

2017-06-06 03:34 UTC, mohierf commented on alignak/objects/config.py
> +        # # Check that a default realm (and only one) is defined
You are right :wink:

2017-06-06 05:18 UTC, mohierf commented
@ddurieux : imho no rebase/squash this PR. leaving the 2 commits as is is correct...

2017-06-08 18:48 UTC, merged